DROP TABLE IF EXISTS PAY_VYNE_TRANSACTION;
CREATE TABLE PAY_VYNE_TRANSACTION (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    STATUS VARCHAR(16) NOT NULL,
    aDATE TIMESTAMP NOT NULL DEFAULT NOW(),
    AMOUNT DOUBLE NOT NULL,
    CURRENCY VARCHAR(16) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL
);